version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:16-alpine
    container_name: memory_business_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: memory_business_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Application
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: memory_business_api
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:postgres@db:5432/memory_business_db
      PROJECT_NAME: Memory Business API
      VERSION: 1.0.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
